// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvDIaX5HNmF2XIbsKgpUkRD6E6CUDsVmQ',
    appId: '1:116928227401:web:72a71d212d2d9034b83798',
    messagingSenderId: '116928227401',
    projectId: 'crudoperations-7fbab',
    authDomain: 'crudoperations-7fbab.firebaseapp.com',
    storageBucket: 'crudoperations-7fbab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD826w1rXOXAalqGtaZl8IdeJnc41eL3_Y',
    appId: '1:116928227401:android:8ac578e5ba05d31eb83798',
    messagingSenderId: '116928227401',
    projectId: 'crudoperations-7fbab',
    storageBucket: 'crudoperations-7fbab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7p89j2ON2UFrUKRcZRRMJLIZfZACym80',
    appId: '1:116928227401:ios:aabdb2cb52eb9a38b83798',
    messagingSenderId: '116928227401',
    projectId: 'crudoperations-7fbab',
    storageBucket: 'crudoperations-7fbab.appspot.com',
    iosBundleId: 'com.example.crudOp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7p89j2ON2UFrUKRcZRRMJLIZfZACym80',
    appId: '1:116928227401:ios:aabdb2cb52eb9a38b83798',
    messagingSenderId: '116928227401',
    projectId: 'crudoperations-7fbab',
    storageBucket: 'crudoperations-7fbab.appspot.com',
    iosBundleId: 'com.example.crudOp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvDIaX5HNmF2XIbsKgpUkRD6E6CUDsVmQ',
    appId: '1:116928227401:web:9994f0a039216937b83798',
    messagingSenderId: '116928227401',
    projectId: 'crudoperations-7fbab',
    authDomain: 'crudoperations-7fbab.firebaseapp.com',
    storageBucket: 'crudoperations-7fbab.appspot.com',
  );
}
